on:
  push:
    tags:
      - 'v*' # Match tags like v1.0, v1.2.3, etc.

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the token has the correct permissions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read CHANGELOG.md
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md

      - name: Extract latest release notes
        id: extract_changelog
        run: |
          # Extract the tag (without 'refs/tags/' prefix) and assign it to a variable
          TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')

          # Use sed to extract the release notes for the current tag
          CHANGELOG=$(echo "${{ steps.changelog.outputs.content }}" | sed -n "/## \[$TAG/,/## \[v/p" | sed '$d')

          # Set the extracted changelog as an output variable
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token provided by Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
            ${{ steps.extract_changelog.outputs.changelog }}
          draft: false
          prerelease: false
