on:
  push:
    tags:
      - 'v*' # Match tags like v1.0, v1.2.3, etc.

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the token has the correct permissions
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract latest release notes
        id: extract_changelog
        run: |
          # Extract the tag (without 'refs/tags/' prefix) and assign it to a variable
          TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')

          # Extract the latest release notes from the CHANGELOG.md for the given tag
          CHANGELOG=$(awk '/^## \[v/ {if (p) exit; } /^## \['"$TAG"'/ {p=1} p' CHANGELOG.md)

          # Set the changelog as an output variable
          echo "::set-output name=changelog::$CHANGELOG"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token provided by Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
            ${{ steps.extract_changelog.outputs.changelog }}
          draft: false
          prerelease: false
